### ISSUE TITLE
Does not work with SX OS

### ISSUE THREAD

**Issue by snoofly** [pixel-stuck/reboot_to_rcm#2]
reboot_to_rcm enables loading various payloads successfully like hekate, but trying to run payload.bin from SX OS gives following issues:

a) If no license files are present (request and dat), SX OS boot screen appears and the information creating license_request.dat is done, but when trying to boot either CFW or OFW, black screen is shown.

b) If license files are already present, boot screen flashes up for a split second then black screen remains.

In both cases, a 12s power down is required to reboot.

**Comment by snoofly** [comment]
I expect this is more a scenario for TX to investigate their payload compatibility as reboot_to_rcm simply sets a register bit, but thought I'd leave it here for information.

**Comment by pixel-stuck** [comment]
All this does is reboot you into RCM mode. It's not really possible for it to cause any issues, afaik. Closing.

**Comment by snoofly** [comment]
Sure understood, I'm dropping a note on the TX forum. Thanks for the quick reply.
