### ISSUE TITLE
MAKE: warning: implicit declaration of function 'fatalSimple' [-Wimplicit-function-declaration

### ISSUE THREAD

**Issue by samsquanch01** [pixel-stuck/reboot_to_rcm#3]
Wsl
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm 

ERROR:

make
main.c
/mnt/c/Users/Administrator/source/reboot_to_rcm-master/source/main.c: In function '__appInit':
/mnt/c/Users/Administrator/source/reboot_to_rcm-master/source/main.c:27:9: warning: implicit declaration of function 'fatalSimple' [-Wimplicit-function-declaration]
   27 |         fatalSimple(MAKERESULT(MODULE_HBL, 1));
      |         ^~~~~~~~~~~
/mnt/c/Users/Administrator/source/reboot_to_rcm-master/source/main.c:33:5: warning: implicit declaration of function 'fsdevInit'; did you mean nsdevExit'? [-Wimplicit-function-declaration]
   33 |     fsdevInit();
      |     ^~~~~~~~~
      |     nsdevExit
/mnt/c/Users/Administrator/source/reboot_to_rcm-master/source/main.c: In function 'main':
/mnt/c/Users/Administrator/source/reboot_to_rcm-master/source/main.c:40:18: warning: implicit declaration of function 'svcQueryIoMapping'; did you mean 'svcQueryMemoryMapping'? [-Wimplicit-function-declaration]
   40 |     Result res = svcQueryIoMapping(&virt_addr, PMC_PHYS_ADDR, 0xC00);
      |                  ^~~~~~~~~~~~~~~~~
      |                  svcQueryMemoryMapping
linking reboot_to_rcm-master.elf
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.2.0/../../../../aarch64-none-elf/bin/ld: main.o: in function `__appInit':
/mnt/c/Users/Administrator/source/reboot_to_rcm-master/source/main.c:33:(.text.__appInit+0x1c): undefined reference to `fsdevInit'
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.2.0/../../../../aarch64-none-elf/bin/ld: /mnt/c/Users/Administrator/source/reboot_to_rcm-master/source/main.c:27:(.text.__appInit+0x24): undefined reference to `fatalSimple'
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.2.0/../../../../aarch64-none-elf/bin/ld: /mnt/c/Users/Administrator/source/reboot_to_rcm-master/source/main.c:31:(.text.__appInit+0x34): undefined reference to `fatalSimple'
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.2.0/../../../../aarch64-none-elf/bin/ld: /mnt/c/Users/Administrator/source/reboot_to_rcm-master/source/main.c:33:(.text.__appInit+0x3c): undefined reference to `fsdevInit'
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.2.0/../../../../aarch64-none-elf/bin/ld: main.o: in function `main':
/mnt/c/Users/Administrator/source/reboot_to_rcm-master/source/main.c:40:(.text.startup.main+0x1c): undefined reference to `svcQueryIoMapping'
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.2.0/../../../../aarch64-none-elf/bin/ld: /mnt/c/Users/Administrator/source/reboot_to_rcm-master/source/main.c:42:(.text.startup.main+0x48): undefined reference to `fatalSimple'
collect2: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/libnx/switch_rules:81: /mnt/c/Users/Administrator/source/reboot_to_rcm-master/reboot_to_rcm-master.elf] Error 1   

Any clue what to do?

**Comment by pixel-stuck** [comment]
reboot_to_rcm hasn't been updated since it was released 5 years ago. In that time, libnx and other tooling has changed drastically, and it needs to be updated for that. Considering the simplicity and lack of any bugs to fix, I'm unlikely to spend the time on that when it's easily possible to just download the release and use it still.

**Comment by samsquanch01** [comment]
facepalm... oh a release... howd I miss that

**Comment by samsquanch01** [comment]
facepalm... oh a release... howd I miss that
